In [2]:
import requests
import pandas as pd

url = "https://api.nbp.pl/api/exchangerates/tables/A/"

response = requests.get(url, timeout=10)
response.raise_for_status()

data = response.json()[0]

df_nbp = pd.DataFrame(data["rates"])
df_nbp["effectiveDate"] = data["effectiveDate"]
df_nbp["tableNo"] = data["no"]
df_nbp = df_nbp[["effectiveDate", "tableNo", "currency", "code", "mid"]]

df_nbp.head(100)

,effectiveDate,tableNo,currency,code,mid
0,2026-03-20,055/A/NBP/2026,bat (Tajlandia),THB,0.113000
1,2026-03-20,055/A/NBP/2026,dolar amerykański,USD,3.703200
2,2026-03-20,055/A/NBP/2026,dolar australijski,AUD,2.616300
3,2026-03-20,055/A/NBP/2026,dolar Hongkongu,HKD,0.472600
4,2026-03-20,055/A/NBP/2026,dolar kanadyjski,CAD,2.699300
5,2026-03-20,055/A/NBP/2026,dolar nowozelandzki,NZD,2.171400
6,2026-03-20,055/A/NBP/2026,dolar singapurski,SGD,2.892700
7,2026-03-20,055/A/NBP/2026,euro,EUR,4.276800
8,2026-03-20,055/A/NBP/2026,forint (Węgry),HUF,0.010889
9,2026-03-20,055/A/NBP/2026,frank szwajcarski,CHF,4.696900
10,2026-03-20,055/A/NBP/2026,funt szterling,GBP,4.955700
11,2026-03-20,055/A/NBP/2026,hrywna (Ukraina),UAH,0.084400
12,2026-03-20,055/A/NBP/2026,jen (Japonia),JPY,0.023316
13,2026-03-20,055/A/NBP/2026,korona czeska,CZK,0.174500
14,2026-03-20,055/A/NBP/2026,korona duńska,DKK,0.572400
15,2026-03-20,055/A/NBP/2026,korona islandzka,ISK,0.029741
16,2026-03-20,055/A/NBP/2026,korona norweska,NOK,0.387700
17,2026-03-20,055/A/NBP/2026,korona szwedzka,SEK,0.397000
18,2026-03-20,055/A/NBP/2026,lej rumuński,RON,0.839400
19,2026-03-20,055/A/NBP/2026,lira turecka,TRY,0.083600
20,2026-03-20,055/A/NBP/2026,nowy izraelski szekel,ILS,1.190800
21,2026-03-20,055/A/NBP/2026,peso chilijskie,CLP,0.004054
22,2026-03-20,055/A/NBP/2026,peso filipińskie,PHP,0.061900
23,2026-03-20,055/A/NBP/2026,peso meksykańskie,MXN,0.207900
24,2026-03-20,055/A/NBP/2026,rand (Republika Południowej Afryki),ZAR,0.218500
25,2026-03-20,055/A/NBP/2026,real (Brazylia),BRL,0.709300
26,2026-03-20,055/A/NBP/2026,ringgit (Malezja),MYR,0.940000
27,2026-03-20,055/A/NBP/2026,rupia indonezyjska,IDR,0.000218
28,2026-03-20,055/A/NBP/2026,rupia indyjska,INR,0.039506
29,2026-03-20,055/A/NBP/2026,won południowokoreański,KRW,0.002473
30,2026-03-20,055/A/NBP/2026,yuan renminbi (Chiny),CNY,0.537600
31,2026-03-20,055/A/NBP/2026,SDR (MFW),XDR,5.057400

In [4]:
df_nbp.isna().sum()

effectiveDate    0
tableNo          0
currency         0
code             0
mid              0
dtype: int64

In [5]:
df_nbp.describe(include="all")

       effectiveDate         tableNo         currency code        mid
count             32              32               32   32  32.000000
unique             1               1               32   32        NaN
top       2026-03-20  055/A/NBP/2026  bat (Tajlandia)  THB        NaN
freq              32              32                1    1        NaN
mean             NaN             NaN              NaN  NaN   1.255328
std              NaN             NaN              NaN  NaN   1.663664
min              NaN             NaN              NaN  NaN   0.000218
25%              NaN             NaN              NaN  NaN   0.078175
50%              NaN             NaN              NaN  NaN   0.434800
75%              NaN             NaN              NaN  NaN   2.282625
max              NaN             NaN              NaN  NaN   5.057400

effectiveDate    2026-03-202026-03-202026-03-202026-03-202026-0...
tableNo          055/A/NBP/2026055/A/NBP/2026055/A/NBP/2026055/...
currency         bat (Tajlandia)dolar amerykańskidolar australi...
code             THBUSDAUDHKDCADNZDSGDEURHUFCHFGBPUAHJPYCZKDKKI...
mid                                                      40.170497
dtype: object